repository:
  has_wiki: false
  has_projects: false
  has_downloads: false
  delete_branch_on_merge: true

branches:
  - name: main
    protection:
      required_pull_request_reviews: null
      required_status_checks: null
      enforce_admins: false
      restrictions: null
